name: big-data
channels:
  - conda-forge
dependencies:
  - python=3.7
  - asyncssh
  - bokeh=2.0
  - bs4
  - dask
  - dask-jobqueue
  - dask-ml
  - dask-xgboost
  - faker
  - feather-format
  - findspark
  - h5py
  - ipykernel
  - ipywidgets
  - jupyterlab
  - jupytext
  - lorem
  - lxml
  - matplotlib
  - nbserverproxy
  - nodejs
  - nomkl
  - numba
  - numpy
  - pandas
  - pip
  - pip:
    - dask_labextension
    - mimesis
  - pyarrow
  - pyspark=2.3.1
  - pytables
  - python-graphviz
  - requests
  - scikit-learn
  - seaborn
  - tornado
  - tqdm
  - xarray
