title: Python tools for Big data
author: Pierre Navaro
logo: images/logoR2-Noir.png

latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_extended_syntax: true

execute:
  execute_notebooks: force

html:
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://pnavaro.github.io/big-data

repository:
  url: https://github.com/pnavaro/big-data
  branch: master
  path_to_book: notebooks

launch_buttons:
  notebook_interface: "classic" 
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

execute:
  timeout: 300
